---

# ansible-playbook --ask-become-pass homebrew-playbook.yml

- hosts: localhost
  connection: local

  vars:
    homebrew_clear_cache: true
    homebrew_group: admin
    homebrew_user: "{{ lookup('env','USER') }}"
    homebrew_upgrade_all_packages: yes
    ansible_python_interpreter: "/usr/bin/python3"

    homebrew_cask_apps_user:
      - appcleaner
      - firefox
      - font-jetbrains-mono
        # - font-meslo-nerd-font
      - font-microsoft-office
      - font-zilla-slab
        # - font-sourcecodepro-nerd-font
        # - font-sourcecodepro-nerd-font-mono
      - google-chrome
      - imagealpha
      - imageoptim
      - iina
      - microsoft-edge-dev
      - microsoft-teams
      - powershell
        # - pycharm
      - slack
      - transmit
      - transmit-disk
      - vagrant
      - vagrant-manager
      - vlc
      - the-unarchiver

    homebrew_installed_packages_user:
      - autoconf
      - automake
      - asciidoctor
      - azure-cli
      - azure-storage-cpp
      - bat
      - black
      - chamber
      - colordiff
      - direnv
      - docutils
      - fzf
      - gawk
      - gitup
      - git
      - graphviz
      - grc
      - hugo
      - ipv6calc
      - ipcalc
      - jq
      - mr
      - node
      - packer
      - pre-commit
      - pyenv
      - pyenv-virtualenv
      - pyenv-virtualenvwrapper
      - rename                      # rename "s/yml/yaml/" **.yml
      - ruby
      - shellcheck
      - sshpass
      - sphinx-doc
      - terraform-docs
      - tflint
      - tree
      - warrensbox/tap/tfswitch
      - tmux
      - vagrant-completion
      - vim
      - wget
      - yarn

    homebrew_taps_user:
      - colindean/fonts-nonfree     # font-microsoft-office
      - homebrew/cask-fonts
      - homebrew/cask-versions  # microsoft-edge-dev
      - homebrew/services
      - mantoso/tap
      - xen0l/homebrew-taps         # aws-gate

    homebrew_uninstalled_packages_user:
      - python@2

  roles:
    - mantoso-role-homebrew

# ansible-playbook --ask-become-pass homebrew-playbook.yml

...
