---

- name: Install Cask applications.
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "appdir={{ homebrew_cask_appdir }}"
  loop:
    - "{{ homebrew_cask_apps }}"
    - "{{ homebrew_cask_apps_user }}"

...